version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:10
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: 
      - run: 
          command: |
            npm install
            cd functions
            npm install
            cd ../
            npm run build
            npm run deploy:hosting -- --token $FIREBASE_TOKEN
            npm run deploy:functions -- --token $FIREBASE_TOKEN
  
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires: 
            - build
      - deploy:
          requires: 
            - test
          filters:
            branches:
              only: master
