version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
  test:
    docker:
      - image: circleci/node:10
      
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10
      
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          command: |
            npm run build
            npm run deploy:hosting -- --token $FIREBASE_TOKEN
            npm run deploy:functions -- --token $FIREBASE_TOKEN
  
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires: 
            - build
      - deploy:
          requires: 
            - test
          filters:
            branches:
              only: master
