version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: cd functions && npm install && cd ../
      - run: npm run build:nuxt:ci
      - run: npm run build:functions
  test:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: |
            npm install
            cd functions
            npm install
            cd ../
            npm run build:nuxt:ci
            npm run build:functions
            npm run deploy:hosting -- --token $FIREBASE_TOKEN
            npm run deploy:functions -- --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
